# Generated by Django 3.1.7 on 2021-05-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(unique=True, verbose_name='Лицевой номер')),
                ('clnt_type', models.BooleanField(default=0, verbose_name='ЮР лицо')),
                ('clnt_name', models.TextField(blank=True, null=True, verbose_name='Имя клиента')),
                ('abonent_adr', models.TextField(null=True, verbose_name='Адрес')),
                ('inn', models.CharField(max_length=20, null=True, verbose_name='ИНН')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Почта')),
                ('contact', models.CharField(max_length=250, null=True, verbose_name='Контактные данные')),
            ],
            options={
                'verbose_name': 'Списоки клиентов',
                'verbose_name_plural': 'Список клиентов',
            },
        ),
        migrations.CreateModel(
            name='Client_shpd_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(verbose_name='Сервисный номер')),
                ('type_shpd', models.CharField(max_length=50, null=True, verbose_name='Тип интернета')),
                ('tarplan', models.CharField(max_length=50, null=True, verbose_name='Тарифный план')),
                ('ip_adr', models.CharField(max_length=250, null=True, verbose_name='ИП адрес')),
                ('user_name', models.CharField(max_length=50, null=True, verbose_name='Логин')),
                ('user_pass', models.CharField(max_length=50, null=True, verbose_name='Пароль')),
                ('bdate', models.CharField(max_length=50, null=True, verbose_name='Начало действия')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oracle_base.client_lists', to_field='account', verbose_name='Лицевой номер')),
            ],
            options={
                'verbose_name': 'Список услуг интернета',
                'verbose_name_plural': 'Список услуг интернета',
            },
        ),
    ]
