# Generated by Django 3.1.7 on 2021-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_lists',
            name='vip',
            field=models.BooleanField(default=0, verbose_name='VIP'),
        ),
    ]
