# Generated by Django 3.1.7 on 2021-07-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_base', '0004_auto_20210702_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_shpd_info',
            name='adress',
            field=models.CharField(max_length=250, null=True, verbose_name='Адрес'),
        ),
    ]
