# Generated by Django 3.1.7 on 2021-07-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_base', '0005_auto_20210702_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_shpd_info',
            name='bdate',
        ),
        migrations.AlterField(
            model_name='client_shpd_info',
            name='abonplat',
            field=models.IntegerField(blank=True, default=0, verbose_name='Абонплата'),
        ),
        migrations.AlterField(
            model_name='client_shpd_info',
            name='gateway',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Шлюз'),
        ),
        migrations.AlterField(
            model_name='client_shpd_info',
            name='ip_adr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ИП адрес'),
        ),
        migrations.AlterField(
            model_name='client_shpd_info',
            name='mask',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Маска'),
        ),
        migrations.AlterField(
            model_name='client_shpd_info',
            name='tarplan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тарифный план'),
        ),
        migrations.AlterField(
            model_name='client_shpd_info',
            name='type_shpd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип интернета'),
        ),
    ]
