# Generated by Django 3.1.7 on 2021-05-17 16:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager', '0002_auto_20210517_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('create_date',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='task_messages',
            options={'ordering': ('create_date',), 'verbose_name': 'Информация к заявкам', 'verbose_name_plural': 'Информация к заявке'},
        ),
        migrations.AlterModelOptions(
            name='task_status',
            options={'ordering': ('create_date',), 'verbose_name': 'Статус заявки', 'verbose_name_plural': 'Статусы заявок'},
        ),
        migrations.AlterModelOptions(
            name='task_user_work',
            options={'ordering': ('create_date',), 'verbose_name': 'История исполнителя', 'verbose_name_plural': 'История исполнителей'},
        ),
        migrations.AddField(
            model_name='task_status',
            name='create_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, editable=False, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='task_user_work',
            name='create_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, editable=False, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task_messages',
            name='create_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, editable=False, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='task_messages',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task_types',
            name='task_name',
            field=models.CharField(max_length=20, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='task_user_work',
            name='create_user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
