# Generated by Django 3.1.7 on 2021-05-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20210517_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_messages',
            options={'ordering': ('create_date',), 'verbose_name': 'Комментарии к заявке', 'verbose_name_plural': 'Комментарии к заявкам'},
        ),
    ]
