# Generated by Django 3.1.7 on 2021-05-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20210517_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
