# Generated by Django 3.1.7 on 2021-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_task_messages_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_types',
            name='category',
            field=models.CharField(choices=[('tech', 'Техподдержка'), ('abon', 'Абонентский')], max_length=10, null=True, verbose_name='Категория заявки'),
        ),
    ]
