# Generated by Django 3.1.7 on 2021-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_task_types_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('tech', 'Техподдержка'), ('abon', 'Абонентский')], default='tech', max_length=10, null=True, verbose_name='Категория заявки'),
        ),
        migrations.AlterField(
            model_name='task_types',
            name='category',
            field=models.CharField(choices=[('tech', 'Техподдержка'), ('abon', 'Абонентский')], default='tech', max_length=10, null=True, verbose_name='Категория заявки'),
        ),
    ]
