# Generated by Django 3.1.7 on 2021-05-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_auto_20210524_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_messages',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_messages', to='task_manager.task', verbose_name='Заявка'),
        ),
    ]
