# Generated by Django 3.1.7 on 2021-07-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_auto_20210526_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_status',
            options={'verbose_name': 'Статус заявки', 'verbose_name_plural': 'Статусы заявок'},
        ),
        migrations.AlterModelOptions(
            name='task_user_work',
            options={'verbose_name': 'История исполнителя', 'verbose_name_plural': 'История исполнителей'},
        ),
        migrations.RemoveField(
            model_name='task_status',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='task_user_work',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('tech', 'Техподдержка'), ('abon', 'Абонентский')], default='tech', max_length=10, verbose_name='Категория заявки'),
        ),
        migrations.AlterField(
            model_name='task_types',
            name='category',
            field=models.CharField(choices=[('tech', 'Техподдержка'), ('abon', 'Абонентский')], default='tech', max_length=10, verbose_name='Категория заявки'),
        ),
    ]
