# Generated by Django 3.1.7 on 2021-05-17 15:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250, verbose_name='Лицевой номер')),
                ('contact', models.CharField(max_length=250, verbose_name='Контактные данные')),
                ('street', models.CharField(max_length=100, verbose_name='Адрес')),
                ('house', models.CharField(max_length=15, verbose_name='Адрес')),
                ('create_date', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата добавления')),
                ('create_user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявки на подключение',
                'verbose_name_plural': 'Заявки на подключение',
            },
        ),
    ]
