# Generated by Django 3.1.7 on 2021-06-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_client', '0002_auto_20210517_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=15, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Адрес заявки',
                'verbose_name_plural': 'Адреса заявок',
            },
        ),
        migrations.RemoveField(
            model_name='new_client',
            name='house',
        ),
        migrations.RemoveField(
            model_name='new_client',
            name='street',
        ),
        migrations.AddField(
            model_name='new_client',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='new_client',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_client.client_adress', verbose_name='Адрес'),
        ),
    ]
