# Generated by Django 3.1.7 on 2021-06-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_client', '0003_auto_20210628_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_client',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_adress', to='new_client.client_adress', verbose_name='Адрес'),
        ),
    ]
