# Generated by Django 3.1.7 on 2021-05-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_base', '0001_initial'),
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware_ports',
            name='client',
        ),
        migrations.AddField(
            model_name='hardware_ports',
            name='client_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oracle_base.client_shpd_info', verbose_name='Услуга клиента'),
        ),
    ]
