# Generated by Django 3.1.7 on 2021-05-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20210514_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_name', models.CharField(max_length=50, unique=True, verbose_name='Почта')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLAN',
            },
        ),
        migrations.AlterModelOptions(
            name='hardware_adress',
            options={'ordering': ['spot_adress'], 'verbose_name': 'Адрес оборудования', 'verbose_name_plural': 'Адреса оборудования'},
        ),
        migrations.AddField(
            model_name='hardware_ports',
            name='port_vlan',
            field=models.ManyToManyField(to='hardware.Vlan'),
        ),
    ]
