# Generated by Django 3.1.7 on 2021-05-17 11:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0003_auto_20210517_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware_ports',
            name='port_vlan',
            field=models.ManyToManyField(blank=True, to='hardware.Vlan'),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='vlan_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Hardware_connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number_A', models.IntegerField(blank=True, null=True, verbose_name='Номер порта')),
                ('port_number_B', models.IntegerField(blank=True, null=True, verbose_name='Номер порта')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
                ('create_date', models.DateTimeField(db_index=True, default=datetime.datetime.now, editable=False, verbose_name='Дата добавления')),
                ('create_user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hardware_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_A', to='hardware.active_hardware', verbose_name='Оборудование А')),
                ('hardware_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_B', to='hardware.active_hardware', verbose_name='Оборудование Б')),
            ],
            options={
                'verbose_name': 'Соединения коммутаторов',
                'verbose_name_plural': 'Соединения коммутаторов',
            },
        ),
    ]
