# Generated by Django 3.1.7 on 2021-05-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_auto_20210517_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware_ports',
            name='port_vlan',
        ),
        migrations.CreateModel(
            name='Vlan_ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.hardware_ports', verbose_name='Порт')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.vlan', verbose_name='VLAN')),
            ],
            options={
                'verbose_name': 'Порты VLAN',
                'verbose_name_plural': 'Порты VLAN',
            },
        ),
    ]
