# Generated by Django 3.1.7 on 2021-06-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_auto_20210517_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware_ports',
            name='port_vlan',
            field=models.ManyToManyField(blank=True, related_name='vlan_ports', to='hardware.Vlan'),
        ),
    ]
