# Generated by Django 3.1.7 on 2021-06-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_auto_20210604_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware_adress',
            options={'ordering': ['adress'], 'verbose_name': 'Адрес оборудования', 'verbose_name_plural': 'Адреса оборудования'},
        ),
        migrations.RemoveField(
            model_name='hardware_adress',
            name='spot_adress',
        ),
        migrations.AddField(
            model_name='hardware_adress',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='vlan_number',
            field=models.IntegerField(default=0, verbose_name='Номер VLAN'),
            preserve_default=False,
        ),
    ]
