# Generated by Django 3.1.7 on 2021-06-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_auto_20210624_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_hardware',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='active_hardware',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='active_hardware',
            name='login',
        ),
        migrations.RemoveField(
            model_name='active_hardware',
            name='password',
        ),
        migrations.RemoveField(
            model_name='active_hardware',
            name='port_proc',
        ),
        migrations.RemoveField(
            model_name='active_hardware',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='active_hardware',
            name='power',
        ),
        migrations.RemoveField(
            model_name='active_hardware',
            name='status_proc',
        ),
        migrations.AlterField(
            model_name='active_hardware',
            name='ip_adress',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP адрес'),
        ),
    ]
