# Generated by Django 3.1.7 on 2021-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_auto_20210624_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware_adress_history',
            name='change_reason',
        ),
        migrations.AddField(
            model_name='active_hardware',
            name='revision',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='active_hardware',
            name='invt_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='active_hardware',
            name='mac_adress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='MAC адрес'),
        ),
        migrations.DeleteModel(
            name='Change_reason',
        ),
    ]
