# Generated by Django 3.1.7 on 2021-06-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_auto_20210624_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_hardware',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.hardware_adress', verbose_name='Адрес'),
        ),
        migrations.DeleteModel(
            name='Hardware_adress_history',
        ),
    ]
