# Generated by Django 3.1.7 on 2021-06-25 11:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0013_auto_20210625_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_hardware',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='active_hardware',
            name='create_user',
        ),
        migrations.CreateModel(
            name='Active_hardware_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(db_index=True, default=datetime.datetime.now, editable=False, verbose_name='Дата добавления')),
                ('name_hardware', models.CharField(max_length=100, verbose_name='Название')),
                ('serial_num', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('invt_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инвентарный номер')),
                ('revision', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ревизия')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('ip_adress', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP адрес')),
                ('mac_adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='MAC адрес')),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.hardware_adress', verbose_name='Адрес')),
                ('create_user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История оборудования',
                'verbose_name_plural': 'История оборудования',
            },
        ),
    ]
