# Generated by Django 3.1.7 on 2021-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0014_auto_20210625_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_hardware',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
