# Generated by Django 3.1.7 on 2021-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0015_active_hardware_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_hardware',
            name='comment',
        ),
        migrations.AddField(
            model_name='active_hardware_history',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
