# Generated by Django 3.1.7 on 2021-06-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hardware', '0016_auto_20210625_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalActive_hardware',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name_hardware', models.CharField(max_length=100, verbose_name='Название')),
                ('serial_num', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('invt_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инвентарный номер')),
                ('revision', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ревизия')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('ip_adress', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP адрес')),
                ('mac_adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='MAC адрес')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('adress', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.hardware_adress', verbose_name='Адрес')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Активное оборудование',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
