# Generated by Django 3.1.7 on 2021-06-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0017_historicalactive_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalactive_hardware',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
