# Generated by Django 3.1.7 on 2021-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0019_auto_20210625_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalactive_hardware',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
