# Generated by Django 3.1.7 on 2021-06-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0022_auto_20210625_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active_hardware_history',
        ),
    ]
