# Generated by Django 3.1.7 on 2021-06-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0023_delete_active_hardware_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_hardware_history',
            fields=[
                ('id', models.IntegerField()),
                ('history_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_hardware', models.CharField(max_length=100, verbose_name='Название')),
                ('serial_num', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('invt_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инвентарный номер')),
                ('revision', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ревизия')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('ip_adress', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP адрес')),
                ('mac_adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='MAC адрес')),
            ],
            options={
                'db_table': 'hardware_historicalactive_hardware',
                'managed': False,
            },
        ),
    ]
