# Generated by Django 3.1.7 on 2021-06-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0024_active_hardware_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware_ports',
            name='hardware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_ports', to='hardware.active_hardware', verbose_name='Оборудование'),
        ),
    ]
