# Generated by Django 3.1.7 on 2021-06-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0025_auto_20210628_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hardware_connections',
        ),
    ]
